export default [
  `time`,
  `year`,
  `people`,
  `way`,
  `day`,
  `man`,
  `thing`,
  `woman`,
  `life`,
  `child`,
  `world`,
  `school`,
  `state`,
  `family`,
  `student`,
  `group`,
  `country`,
  `problem`,
  `hand`,
  `part`,
  `place`,
  `case`,
  `week`,
  `company`,
  `system`,
  `program`,
  `question`,
  `work`,
  `government`,
  `number`,
  `night`,
  `point`,
  `home`,
  `water`,
  `room`,
  `mother`,
  `area`,
  `money`,
  `story`,
  `fact`,
  `month`,
  `lot`,
  `right`,
  `study`,
  `book`,
  `eye`,
  `job`,
  `word`,
  `business`,
  `issue`,
  `side`,
  `kind`,
  `head`,
  `house`,
  `service`,
  `friend`,
  `father`,
  `power`,
  `hour`,
  `game`,
  `line`,
  `end`,
  `member`,
  `law`,
  `car`,
  `city`,
  `community`,
  `name`,
  `president`,
  `team`,
  `minute`,
  `idea`,
  `kid`,
  `body`,
  `information`,
  `back`,
  `parent`,
  `face`,
  `other`,
  `level`,
  `office`,
  `door`,
  `health`,
  `person`,
  `art`,
  `war`,
  `history`,
  `party`,
  `result`,
  `change`,
  `morning`,
  `reason`,
  `research`,
  `girl`,
  `guy`,
  `food`,
  `moment`,
  `air`,
  `teacher`,
  `force`,
  `education`,
  `foot`,
  `boy`,
  `age`,
  `policy`,
  `process`,
  `music`,
  `market`,
  `sense`,
  `nation`,
  `plan`,
  `college`,
  `interest`,
  `death`,
  `experience`,
  `effect`,
  `use`,
  `class`,
  `control`,
  `care`,
  `field`,
  `development`,
  `role`,
  `effort`,
  `rate`,
  `heart`,
  `drug`,
  `show`,
  `leader`,
  `light`,
  `voice`,
  `wife`,
  `police`,
  `mind`,
  `price`,
  `report`,
  `decision`,
  `son`,
  `view`,
  `relationship`,
  `town`,
  `road`,
  `arm`,
  `difference`,
  `value`,
  `building`,
  `action`,
  `model`,
  `season`,
  `society`,
  `tax`,
  `director`,
  `position`,
  `player`,
  `record`,
  `paper`,
  `space`,
  `ground`,
  `form`,
  `event`,
  `official`,
  `matter`,
  `center`,
  `couple`,
  `site`,
  `project`,
  `activity`,
  `star`,
  `table`,
  `need`,
  `court`,
  `American`,
  `oil`,
  `situation`,
  `cost`,
  `industry`,
  `figure`,
  `street`,
  `image`,
  `phone`,
  `data`,
  `picture`,
  `practice`,
  `piece`,
  `land`,
  `product`,
  `doctor`,
  `wall`,
  `patient`,
  `worker`,
  `news`,
  `test`,
  `movie`,
  `north`,
  `love`,
  `support`,
  `technology`,
  `step`,
  `baby`,
  `computer`,
  `type`,
  `attention`,
  `film`,
  `republican`,
  `tree`,
  `source`,
  `organization`,
  `hair`,
  `look`,
  `century`,
  `evidence`,
  `window`,
  `culture`,
  `chance`,
  `brother`,
  `energy`,
  `period`,
  `course`,
  `summer`,
  `plant`,
  `opportunity`,
  `term`,
  `letter`,
  `condition`,
  `choice`,
  `rule`,
  `daughter`,
  `administration`,
  `south`,
  `husband`,
  `congress`,
  `floor`,
  `campaign`,
  `material`,
  `population`,
  `call`,
  `economy`,
  `hospital`,
  `church`,
  `risk`,
  `fire`,
  `future`,
  `defense`,
  `security`,
  `bank`,
  `west`,
  `sport`,
  `board`,
  `subject`,
  `officer`,
  `rest`,
  `behavior`,
  `performance`,
  `top`,
  `goal`,
  `second`,
  `bed`,
  `order`,
  `author`,
  `blood`,
  `agency`,
  `nature`,
  `color`,
  `store`,
  `sound`,
  `movement`,
  `page`,
  `race`,
  `concern`,
  `series`,
  `language`,
  `response`,
  `animal`,
  `factor`,
  `decade`,
  `article`,
  `east`,
  `artist`,
  `scene`,
  `stock`,
  `career`,
  `treatment`,
  `approach`,
  `size`,
  `dog`,
  `fund`,
  `media`,
  `sign`,
  `thought`,
  `list`,
  `individual`,
  `quality`,
  `pressure`,
  `answer`,
  `resource`,
  `meeting`,
  `disease`,
  `success`,
  `cup`,
  `amount`,
  `ability`,
  `staff`,
  `character`,
  `growth`,
  `loss`,
  `degree`,
  `attack`,
  `region`,
  `television`,
  `box`,
  `TV`,
  `trade`,
  `deal`,
  `election`,
  `feeling`,
  `standard`,
  `bill`,
  `message`,
  `analysis`,
  `benefit`,
  `sex`,
  `lawyer`,
  `section`,
  `glass`,
  `skill`,
  `sister`,
  `professor`,
  `operation`,
  `crime`,
  `stage`,
  `authority`,
  `design`,
  `sort`,
  `one`,
  `knowledge`,
  `gun`,
  `station`,
  `strategy`,
  `truth`,
  `song`,
  `example`,
  `environment`,
  `leg`,
  `public`,
  `executive`,
  `set`,
  `rock`,
  `note`,
  `manager`,
  `help`,
  `network`,
  `science`,
  `memory`,
  `card`,
  `seat`,
  `cell`,
  `trial`,
  `expert`,
  `spring`,
  `firm`,
  `democrat`,
  `radio`,
  `management`,
  `ball`,
  `talk`,
  `theory`,
  `impact`,
  `statement`,
  `charge`,
  `direction`,
  `weapon`,
  `employee`,
  `peace`,
  `base`,
  `pain`,
  `play`,
  `measure`,
  `interview`,
  `chair`,
  `fish`,
  `camera`,
  `structure`,
  `politics`,
  `bit`,
  `weight`,
  `candidate`,
  `production`,
  `trip`,
  `evening`,
  `conference`,
  `unit`,
  `style`,
  `adult`,
  `range`,
  `past`,
  `edge`,
  `writer`,
  `trouble`,
  `challenge`,
  `fear`,
  `shoulder`,
  `institution`,
  `sea`,
  `dream`,
  `bar`,
  `property`,
  `stuff`,
  `detail`,
  `method`,
  `magazine`,
  `hotel`,
  `soldier`,
  `cause`,
  `bag`,
  `heat`,
  `fall`,
  `marriage`,
  `surface`,
  `purpose`,
  `pattern`,
  `skin`,
  `agent`,
  `owner`,
  `machine`,
  `gas`,
  `generation`,
  `cancer`,
  `item`,
  `reality`,
  `coach`,
  `yard`,
  `violence`,
  `investment`,
  `discussion`,
  `finger`,
  `garden`,
  `collection`,
  `task`,
  `partner`,
  `kitchen`,
  `consumer`,
  `shot`,
  `budget`,
  `painting`,
  `scientist`,
  `agreement`,
  `capital`,
  `mouth`,
  `victim`,
  `newspaper`,
  `threat`,
  `responsibility`,
  `attorney`,
  `score`,
  `account`,
  `break`,
  `audience`,
  `dinner`,
  `vote`,
  `debate`,
  `citizen`,
  `majority`,
  `wind`,
  `mission`,
  `customer`,
  `speech`,
  `option`,
  `participant`,
  `forest`,
  `video`,
  `senate`,
  `reform`,
  `access`,
  `restaurant`,
  `judge`,
  `relation`,
  `bird`,
  `opinion`,
  `credit`,
  `corner`,
  `version`,
  `safety`,
  `neighborhood`,
  `act`,
  `troop`,
  `income`,
  `species`,
  `track`,
  `hope`,
  `sky`,
  `freedom`,
  `plane`,
  `object`,
  `attitude`,
  `labor`,
  `concept`,
  `client`,
  `conversation`,
  `variety`,
  `turn`,
  `investigation`,
  `researcher`,
  `press`,
  `conflict`,
  `spirit`,
  `argument`,
  `camp`,
  `brain`,
  `feature`,
  `afternoon`,
  `weekend`,
  `possibility`,
  `insurance`,
  `department`,
  `battle`,
  `beginning`,
  `date`,
  `crisis`,
  `fan`,
  `hole`,
  `element`,
  `vision`,
  `status`,
  `ship`,
  `solution`,
  `stone`,
  `scale`,
  `university`,
  `driver`,
  `attempt`,
  `park`,
  `spot`,
  `lack`,
  `ice`,
  `boat`,
  `sun`,
  `distance`,
  `wood`,
  `truck`,
  `return`,
  `mountain`,
  `survey`,
  `tradition`,
  `winter`,
  `village`,
  `sales`,
  `communication`,
  `run`,
  `screen`,
  `resident`,
  `gold`,
  `club`,
  `farm`,
  `increase`,
  `middle`,
  `presence`,
  `district`,
  `shape`,
  `reader`,
  `contract`,
  `crowd`,
  `apartment`,
  `strength`,
  `band`,
  `horse`,
  `target`,
  `prison`,
  `guard`,
  `demand`,
  `reporter`,
  `text`,
  `share`,
  `tool`,
  `vehicle`,
  `flight`,
  `facility`,
  `understanding`,
  `advantage`,
  `leadership`,
  `pound`,
  `basis`,
  `guest`,
  `sample`,
  `block`,
  `protection`,
  `while`,
  `identity`,
  `title`,
  `lesson`,
  `faith`,
  `river`,
  `living`,
  `technique`,
  `path`,
  `ear`,
  `shop`,
  `folk`,
  `principle`,
  `border`,
  `competition`,
  `claim`,
  `equipment`,
  `critic`,
  `aspect`,
  `failure`,
  `Christmas`,
  `comment`,
  `affair`,
  `procedure`,
  `chairman`,
  `baseball`,
  `egg`,
  `belief`,
  `murder`,
  `gift`,
  `religion`,
  `review`,
  `editor`,
  `coffee`,
  `document`,
  `speed`,
  `influence`,
  `youth`,
  `wave`,
  `move`,
  `quarter`,
  `background`,
  `reaction`,
  `suit`,
  `perspective`,
  `construction`,
  `intelligence`,
  `connection`,
  `shoe`,
  `grade`,
  `context`,
  `committee`,
  `mistake`,
  `focus`,
  `smile`,
  `location`,
  `clothes`,
  `neighbor`,
  `drive`,
  `function`,
  `bone`,
  `average`,
  `wine`,
  `voter`,
  `mean`,
  `learning`,
  `bus`,
  `hell`,
  `category`,
  `victory`,
  `key`,
  `visit`,
  `internet`,
  `medicine`,
  `tour`,
  `photo`,
  `finding`,
  `classroom`,
  `contact`,
  `justice`,
  `pair`,
  `exercise`,
  `knee`,
  `flower`,
  `tape`,
  `supply`,
  `cut`,
  `will`,
  `actor`,
  `birth`,
  `search`,
  `democracy`,
  `circle`,
  `device`,
  `progress`,
  `front`,
  `bottom`,
  `island`,
  `exchange`,
  `studio`,
  `lady`,
  `colleague`,
  `application`,
  `neck`,
  `damage`,
  `plastic`,
  `plate`,
  `writing`,
  `start`,
  `expression`,
  `football`,
  `chicken`,
  `army`,
  `abuse`,
  `theater`,
  `map`,
  `session`,
  `danger`,
  `literature`,
  `rain`,
  `desire`,
  `assessment`,
  `injury`,
  `respect`,
  `fuel`,
  `leaf`,
  `instruction`,
  `fight`,
  `pool`,
  `lead`,
  `engine`,
  `salt`,
  `importance`,
  `metal`,
  `fat`,
  `ticket`,
  `software`,
  `lip`,
  `reading`,
  `lunch`,
  `farmer`,
  `sugar`,
  `planet`,
  `enemy`,
  `athlete`,
  `soul`,
  `panel`,
  `meaning`,
  `mom`,
  `instrument`,
  `weather`,
  `commitment`,
  `pocket`,
  `temperature`,
  `surprise`,
  `poll`,
  `proposal`,
  `consequence`,
  `half`,
  `breath`,
  `sight`,
  `cover`,
  `balance`,
  `minority`,
  `works`,
  `teaching`,
  `aid`,
  `advice`,
  `photograph`,
  `trail`,
  `novel`,
  `code`,
  `jury`,
  `breast`,
  `human`,
  `theme`,
  `storm`,
  `union`,
  `desk`,
  `thanks`,
  `fruit`,
  `conclusion`,
  `shadow`,
  `analyst`,
  `dance`,
  `limit`,
  `regulation`,
  `being`,
  `ring`,
  `revenue`,
  `county`,
  `appearance`,
  `package`,
  `difficulty`,
  `bridge`,
  `train`,
  `e-mail`,
  `trend`,
  `visitor`,
  `loan`,
  `investor`,
  `profit`,
  `crew`,
  `accident`,
  `male`,
  `meal`,
  `hearing`,
  `traffic`,
  `muscle`,
  `notion`,
  `earth`,
  `chest`,
  `cash`,
  `museum`,
  `beauty`,
  `emergency`,
  `stress`,
  `content`,
  `root`,
  `nose`,
  `bottle`,
  `setting`,
  `dress`,
  `file`,
  `outcome`,
  `ad`,
  `duty`,
  `sheet`,
  `extent`,
  `component`,
  `contrast`,
  `zone`,
  `airport`,
  `chief`,
  `shirt`,
  `pilot`,
  `cat`,
  `contribution`,
  `capacity`,
  `estate`,
  `guide`,
  `circumstance`,
  `snow`,
  `politician`,
  `percentage`,
  `meat`,
  `soil`,
  `surgery`,
  `basketball`,
  `golf`,
  `chain`,
  `address`,
  `branch`,
  `combination`,
  `governor`,
  `relief`,
  `user`,
  `dad`,
  `manner`,
  `silence`,
  `rating`,
  `motion`,
  `gender`,
  `fee`,
  `landscape`,
  `bowl`,
  `frame`,
  `host`,
  `hall`,
  `ocean`,
  `row`,
  `producer`,
  `regime`,
  `division`,
  `appeal`,
  `mirror`,
  `tooth`,
  `length`,
  `topic`,
  `variable`,
  `telephone`,
  `perception`,
  `confidence`,
  `bedroom`,
  `secret`,
  `debt`,
  `tank`,
  `nurse`,
  `coverage`,
  `opposition`,
  `bond`,
  `pleasure`,
  `master`,
  `era`,
  `requirement`,
  `check`,
  `stand`,
  `fun`,
  `expectation`,
  `wing`,
  `struggle`,
  `judgment`,
  `beer`,
  `English`,
  `reference`,
  `tear`,
  `doubt`,
  `minister`,
  `hero`,
  `cloud`,
  `winner`,
  `volume`,
  `travel`,
  `seed`,
  `fashion`,
  `pepper`,
  `intervention`,
  `copy`,
  `tip`,
  `welfare`,
  `vegetable`,
  `dish`,
  `beach`,
  `improvement`,
  `opening`,
  `route`,
  `league`,
  `core`,
  `rise`,
  `tie`,
  `holiday`,
  `resolution`,
  `household`,
  `abortion`,
  `witness`,
  `sector`,
  `representative`,
  `black`,
  `incident`,
  `flow`,
  `faculty`,
  `waste`,
  `mass`,
  `experiment`,
  `bomb`,
  `tone`,
  `engineer`,
  `wheel`,
  `female`,
  `promise`,
  `cable`,
  `jew`,
  `cream`,
  `secretary`,
  `gate`,
  `hill`,
  `noise`,
  `grass`,
  `hat`,
  `legislation`,
  `achievement`,
  `drink`,
  `talent`,
  `taste`,
  `characteristic`,
  `milk`,
  `sentence`,
  `height`,
  `physician`,
  `sleep`,
  `ride`,
  `explanation`,
  `campus`,
  `potential`,
  `immigrant`,
  `alternative`,
  `interaction`,
  `column`,
  `personality`,
  `signal`,
  `curriculum`,
  `honor`,
  `passenger`,
  `assistance`,
  `association`,
  `lab`,
  `offer`,
  `criticism`,
  `asset`,
  `depression`,
  `journalist`,
  `prayer`,
  `scholar`,
  `warning`,
  `climate`,
  `cheese`,
  `observation`,
  `childhood`,
  `payment`,
  `sir`,
  `cigarette`,
  `definition`,
  `priority`,
  `bread`,
  `creation`,
  `graduate`,
  `request`,
  `emotion`,
  `universe`,
  `gap`,
  `prosecutor`,
  `mark`,
  `green`,
  `airline`,
  `library`,
  `agenda`,
  `factory`,
  `selection`,
  `roof`,
  `expense`,
  `initiative`,
  `diet`,
  `funding`,
  `therapy`,
  `schedule`,
  `housing`,
  `post`,
  `dark`,
  `steel`,
  `chip`,
  `self`,
  `bike`,
  `tea`,
  `comparison`,
  `settlement`,
  `layer`,
  `description`,
  `wedding`,
  `portion`,
  `territory`,
  `opponent`,
  `link`,
  `lake`,
  `tension`,
  `display`,
  `alcohol`,
  `saving`,
  `gain`,
  `desert`,
  `error`,
  `release`,
  `cop`,
  `walk`,
  `sand`,
  `hit`,
  `print`,
  `passage`,
  `transition`,
  `existence`,
  `album`,
  `participation`,
  `atmosphere`,
  `cycle`,
  `whole`,
  `resistance`,
  `discovery`,
  `exposure`,
  `stream`,
  `sale`,
  `trust`,
  `pot`,
  `coalition`,
  `tale`,
  `knife`,
  `phase`,
  `present`,
  `joke`,
  `coat`,
  `symptom`,
  `manufacturer`,
  `philosophy`,
  `potato`,
  `foundation`,
  `pass`,
  `negotiation`,
  `good`,
  `occasion`,
  `dust`,
  `investigator`,
  `jacket`,
  `reduction`,
  `shift`,
  `suicide`,
  `touch`,
  `substance`,
  `discipline`,
  `iron`,
  `passion`,
  `volunteer`,
  `gene`,
  `enforcement`,
  `sauce`,
  `independence`,
  `marketing`,
  `priest`,
  `advance`,
  `employer`,
  `shock`,
  `illness`,
  `cap`,
  `habit`,
  `juice`,
  `involvement`,
  `Indian`,
  `disaster`,
  `parking`,
  `prospect`,
  `boss`,
  `complaint`,
  `championship`,
  `mystery`,
  `poverty`,
  `entry`,
  `spending`,
  `king`,
  `symbol`,
  `maker`,
  `mood`,
  `emphasis`,
  `boot`,
  `entertainment`,
  `bean`,
  `evaluation`,
  `creature`,
  `commander`,
  `arrangement`,
  `total`,
  `anger`,
  `peak`,
  `disorder`,
  `missile`,
  `wire`,
  `round`,
  `distribution`,
  `transportation`,
  `twin`,
  `command`,
  `commission`,
  `interpretation`,
  `breakfast`,
  `stop`,
  `engineering`,
  `luck`,
  `clinic`,
  `veteran`,
  `tablespoon`,
  `tourist`,
  `tomato`,
  `exception`,
  `butter`,
  `deficit`,
  `bathroom`,
  `objective`,
  `ally`,
  `journey`,
  `reputation`,
  `mixture`,
  `tower`,
  `smoke`,
  `dimension`,
  `toy`,
  `prisoner`,
  `peer`,
  `designer`,
  `personnel`,
  `educator`,
  `relative`,
  `immigration`,
  `belt`,
  `teaspoon`,
  `birthday`,
  `implication`,
  `coast`,
  `supporter`,
  `silver`,
  `teenager`,
  `recognition`,
  `retirement`,
  `flag`,
  `recovery`,
  `watch`,
  `gentleman`,
  `corn`,
  `moon`,
  `throat`,
  `salary`,
  `observer`,
  `publication`,
  `crop`,
  `strike`,
  `phenomenon`,
  `anxiety`,
  `convention`,
  `exhibition`,
  `viewer`,
  `pan`,
  `consultant`,
  `administrator`,
  `mayor`,
  `consideration`,
  `CEO`,
  `estimate`,
  `buck`,
  `poem`,
  `grandmother`,
  `enterprise`,
  `stomach`,
  `suggestion`,
  `mail`,
  `recipe`,
  `preparation`,
  `concert`,
  `intention`,
  `channel`,
  `tube`,
  `drawing`,
  `protein`,
  `absence`,
  `roll`,
  `jail`,
  `diversity`,
  `pace`,
  `employment`,
  `speaker`,
  `impression`,
  `essay`,
  `respondent`,
  `cake`,
  `historian`,
  `specialist`,
  `origin`,
  `approval`,
  `mine`,
  `drop`,
  `count`,
  `depth`,
  `wealth`,
  `disability`,
  `shell`,
  `professional`,
  `pack`,
  `onion`,
  `deputy`,
  `brand`,
  `award`,
  `criteria`,
  `dealer`,
  `utility`,
  `highway`,
  `routine`,
  `wage`,
  `phrase`,
  `ingredient`,
  `stake`,
  `fiber`,
  `activist`,
  `terrorism`,
  `refugee`,
  `hip`,
  `corporation`,
  `assumption`,
  `gear`,
  `barrier`,
  `provision`,
  `killer`,
  `gang`,
  `chemical`,
  `label`,
  `teen`,
  `index`,
  `vacation`,
  `advocate`,
  `draft`,
  `heaven`,
  `drama`,
  `satellite`,
  `wonder`,
  `clock`,
  `chocolate`,
  `ceiling`,
  `advertising`,
  `button`,
  `bell`,
  `rank`,
  `darkness`,
  `clothing`,
  `fence`,
  `portrait`,
  `paint`,
  `survival`,
  `lawsuit`,
  `testimony`,
  `bunch`,
  `beat`,
  `burden`,
  `chamber`,
  `furniture`,
  `cooperation`,
  `string`,
  `ceremony`,
  `cheek`,
  `profile`,
  `mechanism`,
  `penalty`,
  `match`,
  `resort`,
  `destruction`,
  `bear`,
  `tissue`,
  `pant`,
  `stranger`,
  `infection`,
  `cabinet`,
  `apple`,
  `virus`,
  `dispute`,
  `fortune`,
  `assistant`,
  `statistics`,
  `cousin`,
  `white`,
  `port`,
  `electricity`,
  `adviser`,
  `pay`,
  `spokesman`,
  `incentive`,
  `slave`,
  `terror`,
  `expansion`,
  `elite`,
  `dirt`,
  `rice`,
  `bullet`,
  `bible`,
  `chart`,
  `decline`,
  `conservative`,
  `stick`,
  `concentration`,
  `champion`,
  `scenario`,
  `telescope`,
  `reflection`,
  `revolution`,
  `strip`,
  `tournament`,
  `fiction`,
  `lifetime`,
  `recommendation`,
  `senator`,
  `salad`,
  `boundary`,
  `satisfaction`,
  `journal`,
  `bench`,
  `lover`,
  `awareness`,
  `general`,
  `deck`,
  `pole`,
  `mode`,
  `dialogue`,
  `founder`,
  `pride`,
  `aircraft`,
  `delivery`,
  `platform`,
  `finance`,
  `joy`,
  `worth`,
  `singer`,
  `shooting`,
  `offense`,
  `counter`,
  `DNA`,
  `smell`,
  `transfer`,
  `protest`,
  `crash`,
  `craft`,
  `treaty`,
  `terrorist`,
  `insight`,
  `lie`,
  `episode`,
  `fault`,
  `mix`,
  `assault`,
  `stair`,
  `adventure`,
  `proof`,
  `headquarters`,
  `violation`,
  `tongue`,
  `license`,
  `hold`,
  `shelter`,
  `controversy`,
  `entrance`,
  `favorite`,
  `tragedy`,
  `net`,
  `funeral`,
  `profession`,
  `establishment`,
  `imagination`,
  `mask`,
  `presentation`,
  `introduction`,
  `representation`,
  `deer`,
  `partnership`,
  `pollution`,
  `emission`,
  `fate`,
  `earnings`,
  `oven`,
  `distinction`,
  `segment`,
  `poet`,
  `variation`,
  `comfort`,
  `honey`,
  `correspondent`,
  `musician`,
  `significance`,
  `load`,
  `vessel`,
  `storage`,
  `leather`,
  `evolution`,
  `tribe`,
  `shelf`,
  `can`,
  `grandfather`,
  `lawn`,
  `buyer`,
  `dining`,
  `wisdom`,
  `council`,
  `instance`,
  `garlic`,
  `capability`,
  `poetry`,
  `celebrity`,
  `stability`,
  `fantasy`,
  `plot`,
  `framework`,
  `gesture`,
  `psychology`,
  `counselor`,
  `chapter`,
  `fellow`,
  `divorce`,
  `pipe`,
  `math`,
  `shade`,
  `tail`,
  `obligation`,
  `angle`,
  `palm`,
  `custom`,
  `economist`,
  `soup`,
  `celebration`,
  `composition`,
  `pile`,
  `carbon`,
  `scheme`,
  `crack`,
  `frequency`,
  `tobacco`,
  `survivor`,
  `psychologist`,
  `galaxy`,
  `ski`,
  `limitation`,
  `appointment`,
  `preference`,
  `meter`,
  `explosion`,
  `arrest`,
  `fighter`,
  `admission`,
  `hunter`,
  `friendship`,
  `aide`,
  `infant`,
  `porch`,
  `tendency`,
  `uniform`,
  `formation`,
  `scholarship`,
  `reservation`,
  `efficiency`,
  `mall`,
  `scandal`,
  `heel`,
  `privacy`,
  `fabric`,
  `contest`,
  `proportion`,
  `guideline`,
  `rifle`,
  `maintenance`,
  `conviction`,
  `trick`,
  `tent`,
  `examination`,
  `publisher`,
  `French`,
  `myth`,
  `cow`,
  `standing`,
  `tennis`,
  `nerve`,
  `barrel`,
  `bombing`,
  `membership`,
  `ratio`,
  `menu`,
  `purchase`,
  `lifestyle`,
  `humor`,
  `glove`,
  `suspect`,
  `narrative`,
  `photographer`,
  `helicopter`,
  `catholic`,
  `provider`,
  `delay`,
  `stroke`,
  `scope`,
  `punishment`,
  `handful`,
  `horizon`,
  `girlfriend`,
  `cholesterol`,
  `adjustment`,
  `taxpayer`,
  `principal`,
  `motivation`,
  `assignment`,
  `restriction`,
  `Palestinian`,
  `laboratory`,
  `workshop`,
  `auto`,
  `cotton`,
  `motor`,
  `flavor`,
  `sequence`,
  `demonstration`,
  `jet`,
  `consumption`,
  `blade`,
  `medication`,
  `cabin`,
  `edition`,
  `valley`,
  `pitch`,
  `pine`,
  `manufacturing`,
  `christian`,
  `complex`,
  `chef`,
  `discrimination`,
  `German`,
  `boom`,
  `heritage`,
  `God`,
  `shit`,
  `lemon`,
  `economics`,
  `nut`,
  `legacy`,
  `extension`,
  `fly`,
  `battery`,
  `arrival`,
  `orientation`,
  `inflation`,
  `flame`,
  `cluster`,
  `wound`,
  `shower`,
  `flesh`,
  `garage`,
  `operator`,
  `instructor`,
  `comedy`,
  `mortgage`,
  `sanction`,
  `habitat`,
  `grain`,
  `consciousness`,
  `measurement`,
  `province`,
  `ethics`,
  `nomination`,
  `permission`,
  `actress`,
  `summit`,
  `acid`,
  `odds`,
  `frustration`,
  `medium`,
  `grant`,
  `shore`,
  `lung`,
  `discourse`,
  `basket`,
  `competitor`,
  `powder`,
  `ghost`,
  `cookie`,
  `carrier`,
  `swing`,
  `orange`,
  `pet`,
  `miracle`,
  `rhythm`,
  `sin`,
  `charity`,
  `script`,
  `tactic`,
  `identification`,
  `transformation`,
  `headline`,
  `venture`,
  `invasion`,
  `military`,
  `piano`,
  `grocery`,
  `intensity`,
  `blanket`,
  `margin`,
  `hay`,
  `mouse`,
  `rope`,
  `prescription`,
  `brick`,
  `patch`,
  `consensus`,
  `horror`,
  `recording`,
  `painter`,
  `pie`,
  `sake`,
  `gaze`,
  `courage`,
  `pregnancy`,
  `clue`,
  `win`,
  `confusion`,
  `slice`,
  `occupation`,
  `coal`,
  `criminal`,
  `formula`,
  `uncle`,
  `square`,
  `captain`,
  `gallery`,
  `soccer`,
  `defendant`,
  `tunnel`,
  `fitness`,
  `lap`,
  `grave`,
  `toe`,
  `container`,
  `virtue`,
  `architect`,
  `makeup`,
  `inquiry`,
  `rose`,
  `indication`,
  `rail`,
  `anniversary`,
  `couch`,
  `alliance`,
  `hypothesis`,
  `boyfriend`,
  `mess`,
  `legend`,
  `adolescent`,
  `norm`,
  `remark`,
  `reward`,
  `organ`,
  `laughter`,
  `northwest`,
  `counseling`,
  `receiver`,
  `ritual`,
  `insect`,
  `salmon`,
  `favor`,
  `combat`,
  `stem`,
  `surgeon`,
  `physics`,
  `rape`,
  `counsel`,
  `brush`,
  `jeans`,
  `log`,
  `pill`,
  `sculpture`,
  `compound`,
  `flour`,
  `slope`,
  `presidency`,
  `serving`,
  `bishop`,
  `cry`,
  `acceptance`,
  `collapse`,
  `pump`,
  `candy`,
  `evil`,
  `final`,
  `medal`,
  `export`,
  `midnight`,
  `curve`,
  `integrity`,
  `logic`,
  `essence`,
  `closet`,
  `interior`,
  `corridor`,
  `pitcher`,
  `snake`,
  `cross`,
  `weakness`,
  `pig`,
  `cold`,
  `T-shirt`,
  `unemployment`,
  `civilization`,
  `pop`,
  `correlation`,
  `humanity`,
  `developer`,
  `excitement`,
  `beef`,
  `stretch`,
  `architecture`,
  `elbow`,
  `muslim`,
  `allegation`,
  `airplane`,
  `duck`,
  `dose`,
  `lecture`,
  `van`,
  `bay`,
  `suburb`,
  `sandwich`,
  `trunk`,
  `rumor`,
  `implementation`,
  `cloth`,
  `effectiveness`,
  `lens`,
  `reach`,
  `inspector`,
  `fraud`,
  `companion`,
  `nail`,
  `array`,
  `rat`,
  `hallway`,
  `cave`,
  `southwest`,
  `monster`,
  `obstacle`,
  `encounter`,
  `herb`,
  `integration`,
  `crystal`,
  `recession`,
  `wish`,
  `motive`,
  `flood`,
  `pen`,
  `ownership`,
  `nightmare`,
  `notice`,
  `inspection`,
  `supervisor`,
  `arena`,
  `laugh`,
  `diagnosis`,
  `possession`,
  `basement`,
  `prosecution`,
  `announcement`,
  `warrior`,
  `prediction`,
  `bacteria`,
  `questionnaire`,
  `mud`,
  `infrastructure`,
  `privilege`,
  `temple`,
  `broadcast`,
  `wrist`,
  `curtain`,
  `monitor`,
  `pond`,
  `domain`,
  `guilt`,
  `cattle`,
  `playoff`,
  `skirt`,
  `database`,
  `aim`,
  `limb`,
  `ideology`,
  `harm`,
  `railroad`,
  `radiation`,
  `horn`,
  `innovation`,
  `strain`,
  `guitar`,
  `replacement`,
  `dancer`,
  `amendment`,
  `pad`,
  `transmission`,
  `grace`,
  `colony`,
  `adoption`,
  `slide`,
  `civilian`,
  `towel`,
  `particle`,
  `glance`,
  `prize`,
  `landing`,
  `conduct`,
  `blue`,
  `bat`,
  `alarm`,
  `festival`,
  `grip`,
  `freshman`,
  `sweat`,
  `European`,
  `separation`,
  `southeast`,
  `ballot`,
  `rhetoric`,
  `vitamin`,
  `enthusiasm`,
  `wilderness`,
  `mandate`,
  `pause`,
  `excuse`,
  `uncertainty`,
  `chaos`,
  `canvas`,
  `lobby`,
  `format`,
  `trait`,
  `currency`,
  `turkey`,
  `reserve`,
  `beam`,
  `astronomer`,
  `corruption`,
  `contractor`,
  `doctrine`,
  `thumb`,
  `unity`,
  `compromise`,
  `rush`,
  `complexity`,
  `fork`,
  `disk`,
  `suspicion`,
  `lock`,
  `finish`,
  `residence`,
  `shame`,
  `sidewalk`,
  `Olympics`,
  `signature`,
  `rebel`,
  `spouse`,
  `fluid`,
  `pension`,
  `sodium`,
  `blow`,
  `promotion`,
  `forehead`,
  `hook`,
  `detective`,
  `traveler`,
  `compensation`,
  `exit`,
  `attraction`,
  `pickup`,
  `needle`,
  `belly`,
  `portfolio`,
  `shuttle`,
  `engagement`,
  `ankle`,
  `transaction`,
  `counterpart`,
  `rider`,
  `doll`,
  `noon`,
  `exhibit`,
  `carbohydrate`,
  `liberty`,
  `poster`,
  `theology`,
  `oxygen`,
  `magic`,
  `sum`,
  `businessman`,
  `determination`,
  `donor`,
  `pastor`,
  `jazz`,
  `opera`,
  `Japanese`,
  `bite`,
  `acquisition`,
  `pit`,
  `wildlife`,
  `giant`,
  `primary`,
  `equity`,
  `doorway`,
  `departure`,
  `elevator`,
  `guidance`,
  `happiness`,
  `statue`,
  `pursuit`,
  `repair`,
  `gym`,
  `clerk`,
  `Israeli`,
  `envelope`,
  `destination`,
  `fist`,
  `exploration`,
  `bath`,
  `rescue`,
  `indicator`,
  `sunlight`,
  `feedback`,
  `spectrum`,
  `laser`,
  `expertise`,
  `tune`,
  `hint`,
  `parade`,
  `realm`,
  `ban`,
  `therapist`,
  `pizza`,
  `recipient`,
  `bias`,
  `metaphor`,
  `candle`,
  `handle`,
  `worry`,
  `entity`,
  `feel`,
  `lamp`,
  `garbage`,
  `servant`,
  `addition`,
  `inside`,
  `reception`,
  `chin`,
  `necessity`,
  `racism`,
  `starter`,
  `gravity`,
  `prevention`,
  `Arab`,
  `performer`,
  `intent`,
  `inventory`,
  `assembly`,
  `silk`,
  `magnitude`,
  `hostage`,
  `collector`,
  `popularity`,
  `kiss`,
  `alien`,
  `equation`,
  `angel`,
  `switch`,
  `offering`,
  `rage`,
  `photography`,
  `toilet`,
  `Russian`,
  `wake`,
  `gathering`,
  `automobile`,
  `dawn`,
  `tide`,
  `romance`,
  `hardware`,
  `pillow`,
  `kit`,
  `cook`,
  `spread`,
  `continent`,
  `circuit`,
  `sink`,
  `ruling`,
  `shortage`,
  `trap`,
  `fool`,
  `deadline`,
  `ranch`,
  `diamond`,
  `credibility`,
  `import`,
  `sentiment`,
  `cart`,
  `elder`,
  `pro`,
  `inspiration`,
  `quantity`,
  `trailer`,
  `mate`,
  `genius`,
  `monument`,
  `bid`,
  `quest`,
  `sacrifice`,
  `invitation`,
  `accuracy`,
  `juror`,
  `broker`,
  `treasure`,
  `loyalty`,
  `gasoline`,
  `output`,
  `nominee`,
  `diabetes`,
  `jaw`,
  `grief`,
  `rocket`,
  `inmate`,
  `dynamics`,
  `bow`,
  `senior`,
  `dignity`,
  `carpet`,
  `bubble`,
  `buddy`,
  `barn`,
  `sword`,
  `flash`,
  `glory`,
  `drum`,
  `queen`,
  `dilemma`,
  `input`,
  `northeast`,
  `liability`,
  `merchant`,
  `stadium`,
  `defeat`,
  `withdrawal`,
  `refrigerator`,
  `nest`,
  `lane`,
  `ancestor`,
  `steam`,
  `accent`,
  `escape`,
  `cage`,
  `shrimp`,
  `homeland`,
  `rack`,
  `costume`,
  `wolf`,
  `courtroom`,
  `statute`,
  `cartoon`,
  `productivity`,
  `seal`,
  `bug`,
  `aunt`,
  `agriculture`,
  `bankruptcy`,
  `vaccine`,
  `bonus`,
  `collaboration`,
  `orbit`,
  `patience`,
  `patrol`,
  `willingness`,
  `revelation`,
  `rent`,
  `jewelry`,
  `trace`,
  `wagon`,
  `reliability`,
  `ass`,
  `bush`,
  `clip`,
  `thigh`,
  `bull`,
  `drawer`,
  `sheep`,
  `coordinator`,
  `runner`,
  `empire`,
  `cab`,
  `exam`,
  `documentary`,
  `biology`,
  `web`,
  `conspiracy`,
  `catch`,
  `casualty`,
  `republic`,
  `execution`,
  `whale`,
  `instinct`,
  `teammate`,
  `aluminum`,
  `ministry`,
  `verdict`,
  `skull`,
  `self-esteem`,
  `ease`,
  `bee`,
  `practitioner`,
  `loop`,
  `puzzle`,
  `mushroom`,
  `subsidy`,
  `mathematics`,
  `mechanic`,
  `jar`,
  `earthquake`,
  `pork`,
  `creativity`,
  `dessert`,
  `sympathy`,
  `fisherman`,
  `isolation`,
  `sock`,
  `jump`,
  `entrepreneur`,
  `syndrome`,
  `bureau`,
  `workplace`,
  `ambition`,
  `touchdown`,
  `breeze`,
  `christianity`,
  `translation`,
  `gut`,
  `booth`,
  `helmet`,
  `waist`,
  `lion`,
  `accomplishment`,
  `panic`,
  `cast`,
  `cliff`,
  `cord`,
  `cocaine`,
  `illusion`,
  `appreciation`,
  `commissioner`,
  `flexibility`,
  `casino`,
  `tumor`,
  `pulse`,
  `equivalent`,
  `donation`,
  `diary`,
  `sibling`,
  `irony`,
  `spoon`,
  `midst`,
  `alley`,
  `soap`,
  `rival`,
  `pin`,
  `hockey`,
  `supplier`,
  `momentum`,
  `purse`,
  `liquid`,
  `icon`,
  `elephant`,
  `legislature`,
  `associate`,
  `franchise`,
  `bicycle`,
  `fever`,
  `filter`,
  `rabbit`,
  `coin`,
  `organism`,
  `sensation`,
  `stay`,
  `minimum`,
  `conservation`,
  `backyard`,
  `charter`,
  `stove`,
  `consent`,
  `reminder`,
  `placement`,
  `dough`,
  `grandchild`,
  `dam`,
  `outfit`,
  `columnist`,
  `workout`,
  `patent`,
  `quote`,
  `trash`,
  `hormone`,
  `texture`,
  `pencil`,
  `frontier`,
  `spray`,
  `bet`,
  `custody`,
  `banker`,
  `beast`,
  `oak`,
  `notebook`,
  `attendance`,
  `speculation`,
  `shark`,
  `mill`,
  `installation`,
  `tag`,
  `fleet`,
  `catalog`,
  `outsider`,
  `stance`,
  `sensitivity`,
  `debut`,
  `confrontation`,
  `ideal`,
  `constitution`,
  `trainer`,
  `Thanksgiving`,
  `scent`,
  `stack`,
  `eyebrow`,
  `sack`,
  `tray`,
  `pioneer`,
  `textbook`,
  `dot`,
  `wheat`,
  `kingdom`,
  `aisle`,
  `protocol`,
  `marketplace`,
  `terrain`,
  `pasta`,
  `genre`,
  `merit`,
  `planner`,
  `chunk`,
  `discount`,
  `ladder`,
  `jungle`,
  `migration`,
  `hurricane`,
  `retailer`,
  `coup`,
  `ambassador`,
  `density`,
  `curiosity`,
  `aggression`,
  `stimulus`,
  `journalism`,
  `robot`,
  `feather`,
  `sphere`,
  `publicity`,
  `major`,
  `well-being`,
  `validity`,
  `ecosystem`,
  `collar`,
  `weed`,
  `compliance`,
  `streak`,
  `builder`,
  `glimpse`,
  `premise`,
  `specialty`,
  `artifact`,
  `monkey`,
  `mentor`,
  `listener`,
  `lightning`,
  `sleeve`,
  `disappointment`,
  `rib`,
  `debris`,
  `rod`,
  `liberal`,
  `ash`,
  `parish`,
  `slavery`,
  `commodity`,
  `cure`,
  `mineral`,
  `hunger`,
  `equality`,
  `cemetery`,
  `harassment`,
  `fame`,
  `likelihood`,
  `carrot`,
  `toll`,
  `rim`,
  `wheelchair`,
  `squad`,
  `processor`,
  `sponsor`,
  `grin`,
  `chill`,
  `refuge`,
  `legislator`,
  `rally`,
  `programming`,
  `outlet`,
  `vendor`,
  `peanut`,
  `intellectual`,
  `conception`,
  `auction`,
  `steak`,
  `triumph`,
  `shareholder`,
  `conscience`,
  `calculation`,
  `interval`,
  `jurisdiction`,
  `constraint`,
  `expedition`,
  `similarity`,
  `butt`,
  `lid`,
  `bulk`,
  `mortality`,
  `conversion`,
  `patron`,
  `liver`,
  `harmony`,
  `tolerance`,
  `instant`,
  `goat`,
  `blessing`,
  `banana`,
  `running`,
  `palace`,
  `peasant`,
  `grandparent`,
  `lawmaker`,
  `supermarket`,
  `cruise`,
  `plain`,
  `calendar`,
  `widow`,
  `deposit`,
  `beard`,
  `brake`,
  `screening`,
  `impulse`,
  `fur`,
  `predator`,
  `forum`,
  `removal`,
  `autonomy`,
  `thread`,
  `landmark`,
  `offender`,
  `fraction`,
  `tourism`,
  `threshold`,
  `suite`,
  `regulator`,
  `straw`,
  `globe`,
  `objection`,
  `chemistry`,
  `blast`,
  `denial`,
  `rental`,
  `fragment`,
  `warmth`,
  `undergraduate`,
  `headache`,
  `policeman`,
  `yield`,
  `projection`,
  `mention`,
  `graduation`,
  `mansion`,
  `regard`,
  `grape`,
  `cottage`,
  `driveway`,
  `charm`,
  `sexuality`,
  `clay`,
  `balloon`,
  `invention`,
  `ego`,
  `fare`,
  `homework`,
  `disc`,
  `sofa`,
  `guarantee`,
  `availability`,
  `radar`,
  `leave`,
  `permit`,
  `sweater`,
  `rehabilitation`,
  `retreat`,
  `molecule`,
  `youngster`,
  `premium`,
  `accountability`,
  `fatigue`,
  `marker`,
  `bucket`,
  `confession`,
  `marble`,
  `twist`,
  `defender`,
  `transport`,
  `surveillance`,
  `technician`,
  `arrow`,
  `trauma`,
  `ribbon`,
  `meantime`,
  `harvest`,
  `spy`,
  `slot`,
  `riot`,
  `nutrient`,
  `citizenship`,
  `sovereignty`,
  `ridge`,
  `lighting`,
  `contributor`,
  `transit`,
  `seminar`,
  `electronics`,
  `shorts`,
  `accusation`,
  `cue`,
  `bride`,
  `biography`,
  `hazard`,
  `tile`,
  `foreigner`,
  `launch`,
  `convenience`,
  `delight`,
  `timber`,
  `plea`,
  `bulb`,
  `devil`,
  `bolt`,
  `cargo`,
  `spine`,
  `seller`,
  `dock`,
  `fog`,
  `diplomat`,
  `summary`,
  `missionary`,
  `epidemic`,
  `warehouse`,
  `butterfly`,
  `bronze`,
  `praise`,
  `vacuum`,
  `stereotype`,
  `sensor`,
  `laundry`,
  `manual`,
  `pistol`,
  `plaintiff`,
  `apology`,
];

export const pluralExceptions = {
  family: 'families',
  country: 'countries',
  company: 'companies',
  money: 'monies',
  story: 'stories',
  study: 'studies',
  business: 'businesses',
  city: 'cities',
  community: 'communities',
  body: 'bodies',
  history: 'histories',
  party: 'parties',
  research: 'research',
  policy: 'policies',
  process: 'processes',
  class: 'classes',
  society: 'societies',
  activity: 'activities',
  industry: 'industries',
  news: 'news',
  technology: 'technologies',
  baby: 'babies',
  century: 'centuries',
  energy: 'energies',
  opportunity: 'opportunities',
  south: 'souths',
  congress: 'congresses',
  economy: 'economies',
  church: 'churches',
  security: 'securities',
  agency: 'agencies',
  series: 'serieses',
  approach: 'approaches',
  quality: 'qualities',
  success: 'successes',
  ability: 'abilities',
  loss: 'losses',
  analysis: 'analyses',
  glass: 'glasses',
  authority: 'authorities',
  strategy: 'strategies',
  memory: 'memories',
  theory: 'theories',
  fish: 'fishes',
  property: 'properties',
  gas: 'gasses',
  reality: 'realities',
  coach: 'coaches',
  responsibility: 'responsibilities',
  majority: 'majorities',
  speech: 'speeches',
  access: 'accesses',
  safety: 'safeties',
  species: 'species',
  sky: 'skies',
  variety: 'varieties',
  press: 'presses',
  possibility: 'possibilities',
  crisis: 'crises',
  status: 'statuses',
  university: 'universities',
  sales: 'sales',
  facility: 'facilities',
  basis: 'basises',
  identity: 'identities',
  Christmas: 'Christmases',
  focus: 'foci',
  clothes: 'clothes',
  bus: 'busses',
  category: 'categories',
  victory: 'victories',
  supply: 'supplies',
  birth: 'births',
  search: 'searches',
  democracy: 'democracies',
  progress: 'progresses',
  lady: 'ladies',
  army: 'armies',
  injury: 'injuries',
  lunch: 'lunches',
  enemy: 'enemies',
  minority: 'minorities',
  works: 'works',
  jury: 'juries',
  thanks: 'thanks',
  county: 'counties',
  difficulty: 'difficulties',
  earth: 'earths',
  cash: 'cash',
  beauty: 'beauties',
  emergency: 'emergencies',
  stress: 'stresses',
  dress: 'dresses',
  duty: 'duties',
  capacity: 'capacities',
  surgery: 'surgeries',
  address: 'addresses',
  branch: 'branches',
  English: 'English',
  copy: 'copies',
  dish: 'dishes',
  beach: 'beaches',
  witness: 'witnesses',
  faculty: 'faculties',
  mass: 'masses',
  secretary: 'secretaries',
  grass: 'grasses',
  campus: 'campuses',
  personality: 'personalities',
  priority: 'priorities',
  library: 'libraries',
  factory: 'factories',
  therapy: 'therapies',
  territory: 'territories',
  discovery: 'discoveries',
  philosophy: 'philosophies',
  pass: 'passes',
  touch: 'touches',
  illness: 'illnesses',
  boss: 'bosses',
  mystery: 'mysteries',
  poverty: 'poverties',
  entry: 'entries',
  emphasis: 'emphases',
  ally: 'allies',
  journey: 'journies',
  recovery: 'recoveries',
  watch: 'watches',
  salary: 'salaries',
  anxiety: 'anxieties',
  diversity: 'diversities',
  disability: 'disabilities',
  deputy: 'deputies',
  utility: 'utilities',
  darkness: 'darknesses',
  testimony: 'testimonies',
  bunch: 'bunches',
  ceremony: 'ceremonies',
  penalty: 'penalties',
  match: 'matches',
  virus: 'viruses',
  statistics: 'statistics',
  electricity: 'electricities',
  boundary: 'boundaries',
  bench: 'benches',
  awareness: 'awarenesses',
  delivery: 'deliveries',
  crash: 'crashes',
  treaty: 'treaties',
  headquarters: 'headquarters',
  controversy: 'controversies',
  tragedy: 'tragedies',
  earnings: 'earnings',
  honey: 'honies',
  capability: 'capabilities',
  poetry: 'poetries',
  celebrity: 'celebrities',
  stability: 'stabilities',
  fantasy: 'fantasies',
  psychology: 'psychologies',
  frequency: 'frequencies',
  galaxy: 'galaxies',
  porch: 'porches',
  tendency: 'tendencies',
  efficiency: 'efficiencies',
  privacy: 'privacies',
  French: 'French',
  tennis: 'tennises',
  delay: 'delays',
  laboratory: 'laboratories',
  pitch: 'pitches',
  legacy: 'legacies',
  fly: 'flies',
  battery: 'batteries',
  flesh: 'flesh',
  comedy: 'comedies',
  consciousness: 'consciousnesses',
  ethics: 'ethics',
  actress: 'actresses',
  odds: 'odds',
  charity: 'charities',
  military: 'militaries',
  grocery: 'groceries',
  intensity: 'intensities',
  hay: 'hay',
  patch: 'patches',
  consensus: 'consensuses',
  pregnancy: 'pregnancies',
  gallery: 'galleries',
  fitness: 'fitnesses',
  inquiry: 'inquiries',
  anniversary: 'anniversaries',
  couch: 'couches',
  hypothesis: 'hypotheses',
  mess: 'messes',
  physics: 'physics',
  brush: 'brushes',
  jeans: 'jeans',
  presidency: 'presidencies',
  cry: 'cries',
  candy: 'candies',
  integrity: 'integrities',
  cross: 'crosses',
  weakness: 'weaknesses',
  humanity: 'humanities',
  stretch: 'stretches',
  sandwich: 'sandwiches',
  effectiveness: 'effectiveness',
  lens: 'lenses',
  reach: 'reaches',
  wish: 'wishes',
  diagnosis: 'diagnoses',
  ideology: 'ideologies',
  colony: 'colonies',
  wilderness: 'wildernesses',
  uncertainty: 'uncertainties',
  chaos: 'chaos',
  canvas: 'canvases',
  lobby: 'lobbies',
  currency: 'currencies',
  unity: 'unities',
  rush: 'rushes',
  complexity: 'complexities',
  finish: 'finishes',
  Olympics: 'Olympics',
  belly: 'bellies',
  liberty: 'liberties',
  theology: 'theologies',
  primary: 'primaries',
  equity: 'equities',
  doorway: 'doorways',
  happiness: 'happinesses',
  bias: 'biases',
  worry: 'worries',
  entity: 'entities',
  necessity: 'necessities',
  gravity: 'gravities',
  inventory: 'inventories',
  assembly: 'assemblies',
  popularity: 'popularities',
  kiss: 'kisses',
  switch: 'switches',
  photography: 'photographies',
  ranch: 'ranches',
  credibility: 'credibilities',
  quantity: 'quantities',
  genius: 'geniuses',
  accuracy: 'accuracies',
  loyalty: 'loyalties',
  diabetes: 'diabetes',
  dynamics: 'dynamics',
  dignity: 'dignities',
  buddy: 'buddies',
  flash: 'flashes',
  glory: 'glories',
  liability: 'liabilities',
  productivity: 'productivities',
  bankruptcy: 'bankruptcies',
  bonus: 'bonuses',
  willingness: 'willingnesses',
  jewelry: 'jewelries',
  reliability: 'reliabilities',
  ass: 'asses',
  bush: 'bush',
  documentary: 'documentaris',
  biology: 'biologies',
  conspiracy: 'conspiracies',
  catch: 'catches',
  casualty: 'casualties',
  ministry: 'ministries',
  subsidy: 'subsidies',
  mathematics: 'mathematics',
  creativity: 'creativities',
  sympathy: 'sympathies',
  christianity: 'christianities',
  flexibility: 'flexibilities',
  diary: 'diaries',
  irony: 'ironies',
  trash: 'trashes',
  custody: 'custodies',
  sensitivity: 'sensitivities',
  density: 'densities',
  curiosity: 'curiosities',
  stimulus: 'stimuli',
  publicity: 'publicitoes',
  validity: 'validities',
  specialty: 'specialties',
  debris: 'debris',
  ash: 'ashes',
  parish: 'parishes',
  slavery: 'slaveries',
  commodity: 'commodities',
  equality: 'equalities',
  cemetery: 'cemeteries',
  rally: 'rallies',
  similarity: 'similarities',
  mortality: 'mortalities',
  harmony: 'harmonies',
  autonomy: 'autonomies',
  chemistry: 'chemistries',
  sexuality: 'sexualities',
  availability: 'availabilities',
  accountability: 'accountabilities',
  spy: 'spies',
  sovereignty: 'sovereignties',
  electronics: 'electronics',
  shorts: 'shorts',
  biography: 'biographies',
  launch: 'launches',
  summary: 'summaries',
  missionary: 'missionaries',
  butterfly: 'butterflies',
  laundry: 'laundries',
  apology: 'apologies',

  hero: 'heroes',
  potato: 'potatoes',
  tomato: 'tomatoes',
  life: 'lives',
  wife: 'lives',
  knife: 'knives',
  wildlife: 'wildlives',
  foot: 'feet',
  tooth: 'teeth',
  man: `men`,
  woman: `women`,
  chairman: `chairmen`,
  human: `humen`,
  gentleman: `gentlemen`,
  spokesman: `spokesmen`,
  freshman: `freshmen`,
  businessman: `businessmen`,
  fisherman: `fishermen`,
  policeman: `policemen`,

  mouse: `mice`,

  tax: 'taxes',
  box: 'boxes',
  sex: 'sexes',
  index: 'indexes',
  mix: 'mixes',
  complex: 'complexes',

  child: 'children',
  grandchild: 'grandchildren',
  person: 'people',

  sheep: 'sheep',
  shrimp: 'shrimp',
  deer: 'deer',
  aircraft: 'aircraft',
  craft: 'craft',
  economics: 'economics',
  phenomenon: 'phenomena',
};

export const pluralize = noun =>
  pluralExceptions[noun] ? pluralExceptions[noun] : `${noun}s`;
