export const palletes = [
  'boring festival bows',
  'helpful kitchen',
  'important button',
  'load wonder',
  'huge banker decline',
  'suspicions',
  'risky bed casualties',
  'pursuit',
  'job inspiration',
  'pine',
  'ass spoon',
  'doll battery',
  'marine settlement grins',
  'play labors',
  'total absence liberties',
  'japanese density explanation',
  'queen salt',
  'sexy cure lips',
  'expert',
  'perspective fly',
  'champion chemical',
  'space',
  'nice slice',
  'bare woman chill',
  'nearby permit medicine',
  'olympic civilian concept',
  'religious van tunnel',
  'responsible dot mistake',
  'native fur provision',
  'integrated quarter grants',
  
];

export const colors = [
  'pencil warriors',
  'correspondent details',
  'rich park professions',
  'black basement',
  'doll battery',
  'prize weights',
  'drunk rooms',
  'continuous warning cry',
  'vendor',
  'remarkable contracts',
  'glad refuge',
  'glad grains',
  'philosophical breasts',
  'basteria',
];
